[project]
name = "tuizzard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Victor Tavarez", email = "victora.t.nolasco@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "textual>=8.2.8",
]

[project.scripts]
tuizzard = "tuizzard:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
